name: Release Alpha and Propose Stable

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [dev]

jobs:
  publish_alpha:
    uses: OpenVoiceOS/gh-automations/.github/workflows/publish-alpha.yml@dev
    secrets: inherit
    with:
      branch: 'dev'
      version_file: 'ovos_stt_plugin_wav2vec/version.py'
      update_changelog: true
      publish_prerelease: true
      changelog_max_issues: 100
      notify_matrix: true
      publish_pypi: true
